# This file was generated by an experimental feature called 'Gather'.
#
#     The intent is that it contains only the code required to produce
#     the same results as the cell originally selected for gathering.
#     Please note that the Python analysis is quite conservative, so if
#     it is unsure whether a line of code is necessary for execution, it
#     will err on the side of including it.
#
# Please let us know if you are satisfied with what was gathered here:
# https://aka.ms/gathersurvey

# %%
## Gather not available
